apiVersion: v1
kind: ImageTag
metadata:
  name: app-tag
spec:
  tags:
    - name: v1.0-dev
      from:
        kind: ImageStreamTag
        name: app:latest
      importPolicy:
        scheduled: true
    - name: v1.0-stage
      from:
        kind: ImageStreamTag
        name: app:v1.0-dev
      importPolicy:
        scheduled: false
    - name: v1.0-prod
      from:
        kind: ImageStreamTag
        name: app:v1.0-stage
      importPolicy:
        scheduled: false 